import Head from 'next/head';
import Image from 'next/image';
import Test1 from '../public/test1.png';
import Test2 from '../public/test2.png';
import Test3 from '../public/test3.png';
import { resource } from '@/shared/resource';
import LinkItem from '@/components/LinkItem';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center mb-[20px]">
        <div className="w-[1600px] ">
          <div className="flex flex-col gap-[160px]">
            <div className="">
              <h2 className="font-bold text-2xl mb-6">Team Project</h2>

              <div className="w-full grid grid-cols-3 gap-4">
                {resource.map((data) => (
                  <LinkItem key={data?.id} {...data} />
                ))}
              </div>
            </div>

            <div className="">
              <h2 className="font-bold text-2xl mb-6">Personal Project</h2>

              <div className="w-full grid grid-cols-3 gap-4">
                {resource.map((data) => (
                  <LinkItem key={data?.id} {...data} />
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
